
<div class="">        
<div style="display: block;text-align: center;background: #2b542c;padding: 5px;color:white;font-weight: bold">CODE DE BONNE CONDUITE</div>

        <div style="text-align:justify">
		<p style="margin: 7.5pt 0cm;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;"><strong><span style='font-size:15px;font-family: "Trebuchet MS", sans-serif;color: black;'>Introduction</span></strong></p>
<p style="margin: 6pt 0cm;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-indent: 0px;text-decoration: none;text-align: justify;"><span style='font-size:15px;font-family: "Trebuchet MS", sans-serif;color: black;'>&nbsp;</span></p>
<p style="margin: 6pt 0cm;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-indent: 0px;text-decoration: none;text-align: justify;"><span style='font-size:15px;font-family: "Trebuchet MS", sans-serif;color: black;'>La Guin&eacute;e est &agrave; son quatri&egrave;me Recensement G&eacute;n&eacute;ral&nbsp;&nbsp;de la Population et de l&apos;Habitation (RGPH-4)&nbsp;&nbsp;qui a pour principal objectif de r&eacute;pondre aux besoins statistiques essentiels de la nation guin&eacute;enne. En plus, l&apos;organisation du 4&egrave;me Recensement G&eacute;n&eacute;ral de la Population et de l&rsquo;Habitation RGPH-4&nbsp;&nbsp;va contribuer &agrave; la mise &agrave; disposition d&apos;un certain nombre de produits, &agrave; l&apos;am&eacute;lioration de la connaissance des caract&eacute;ristiques d&eacute;mographiques et socio- &eacute;conomiques de la population guin&eacute;enne et de sa dynamique.</span></p>
<p style="margin: 6pt 0cm;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-indent: 0px;text-decoration: none;text-align: justify;"><span style='font-size:15px;font-family: "Trebuchet MS", sans-serif;color: black;'>En vue de mettre &agrave; la disposition du projet des ressources humaines de qualit&eacute;, un code de bonne conduite est con&ccedil;u à l’attention du personnel intervenant sur le projet.</span></p>
<p style="margin: 6pt 0cm;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-indent: 0px;text-decoration: none;text-align: justify;"><span style='font-size:15px;font-family: "Trebuchet MS", sans-serif;color: black;'>Ce code de bonne conduite s&apos;applique &agrave; l&apos;ensemble du personnel du Recensement G&eacute;n&eacute;ral de la Population et de l&rsquo;Habitation RGPH-4 &nbsp;; notamment :&nbsp;</span></p>
<p style="margin: 6pt 0cm;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-indent: 0px;text-decoration: none;text-align: justify;"><span style='font-size:15px;font-family: "Trebuchet MS", sans-serif;color: black;'>&nbsp;</span></p>
<p style="margin: 0cm 0cm 7.5pt 18pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-decoration: none;text-indent: -18pt;"><span style="font-family: -webkit-standard, serif;color: black;">-&nbsp;</span><span style='font-family: "Trebuchet MS", sans-serif;color: black;'>Le personnel de l&apos;INS intervenant sur le projet&nbsp;;</span></p>
<p style="margin: 0cm 0cm 7.5pt 18pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-decoration: none;text-indent: -18pt;"><span style="font-family: -webkit-standard, serif;color: black;">-&nbsp;</span><span style='font-family: "Trebuchet MS", sans-serif;color: black;'>Les superviseurs permanents&nbsp;;</span></p>
<p style="margin: 0cm 0cm 7.5pt 18pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-decoration: none;text-indent: -18pt;"><span style="font-family: -webkit-standard, serif;color: black;">-&nbsp;</span><span style='font-family: "Trebuchet MS", sans-serif;color: black;'>Les assistants administratifs&nbsp;;</span></p>
<p style="margin: 0cm 0cm 7.5pt 18pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-decoration: none;text-indent: -18pt;"><span style="font-family: -webkit-standard, serif;color: black;">-&nbsp;</span><span style='font-family: "Trebuchet MS", sans-serif;color: black;'>Les assistants comptables&nbsp;;</span></p>
<p style="margin: 0cm 0cm 7.5pt 18pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-decoration: none;text-indent: -18pt;"><span style="font-family: -webkit-standard, serif;color: black;">-&nbsp;</span><span style='font-family: "Trebuchet MS", sans-serif;color: black;'>Les g&eacute;omaticiens ;&nbsp;</span></p>
<p style="margin: 0cm 0cm 7.5pt 18pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-decoration: none;text-indent: -18pt;"><span style="font-family: -webkit-standard, serif;color: black;">-&nbsp;</span><span style='font-family: "Trebuchet MS", sans-serif;color: black;'>Les assistants TIC&nbsp;;</span></p>
<p style="margin: 0cm 0cm 7.5pt 18pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-decoration: none;text-indent: -18pt;"><span style="font-family: -webkit-standard, serif;color: black;">-&nbsp;</span><span style='font-family: "Trebuchet MS", sans-serif;color: black;'>Les agents pr&eacute;parateurs de dossiers cartographiques&nbsp;;</span></p>
<p style="margin: 0cm 0cm 7.5pt 18pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-decoration: none;text-indent: -18pt;"><span style="font-family: -webkit-standard, serif;color: black;">-&nbsp;</span><span style='font-family: "Trebuchet MS", sans-serif;color: black;'>Les chefs d&apos;&eacute;quipe&nbsp;;</span></p>
<p style="margin: 0cm 0cm 7.5pt 18pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-decoration: none;text-indent: -18pt;"><span style="font-family: -webkit-standard, serif;color: black;">-&nbsp;</span><span style='font-family: "Trebuchet MS", sans-serif;color: black;'>Les agents cartographes&nbsp;;</span></p>
<p style="margin: 0cm 0cm 7.5pt 18pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-decoration: none;text-indent: -18pt;"><span style="font-family: -webkit-standard, serif;color: black;">-&nbsp;</span><span style='font-family: "Trebuchet MS", sans-serif;color: black;'>Les agents recenseurs&nbsp;;</span></p>
<p style="margin: 0cm 0cm 7.5pt 18pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-decoration: none;text-indent: -18pt;"><span style="font-family: -webkit-standard, serif;color: black;">-&nbsp;</span><span style='font-family: "Trebuchet MS", sans-serif;color: black;'>Les appuis logistiques&nbsp;;</span></p>
<p style="margin: 0cm 0cm 7.5pt 18pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-decoration: none;text-indent: -18pt;"><span style="font-family: -webkit-standard, serif;color: black;">-&nbsp;</span><span style='font-family: "Trebuchet MS", sans-serif;color: black;'>Les communicateurs&nbsp;;</span></p>
<p style="margin: 0cm 0cm 7.5pt 18pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-decoration: none;text-indent: -18pt;"><span style="font-family: -webkit-standard, serif;color: black;">-&nbsp;</span><span style='font-family: "Trebuchet MS", sans-serif;color: black;'>Les chauffeurs.</span></p>
<p style="margin: 6pt 0cm;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-indent: 0px;text-decoration: none;text-align: center;background-color: rgb(191, 191, 191);"><strong><span style='font-size:15px;font-family: "Trebuchet MS", sans-serif;color: black;'>PRINCIPALES PRESCRIPTIONS DU CODE DE BONNE CONDUITE</span></strong></p>
<p style="margin: 6pt 0cm;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-indent: 0px;text-decoration: none;text-align: justify;"><span style='font-size:15px;font-family: "Trebuchet MS", sans-serif;color: black;'>Les prescriptions de ce code doivent &ecirc;tre scrupuleusement respect&eacute;es.</span></p>
<p style="margin: 6pt 0cm;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-decoration: none;text-align: justify;text-indent: 35.4pt;"><strong><span style='font-size:15px;font-family: "Trebuchet MS", sans-serif;color: black;'>1-Respect et courtoisie</span></strong></p>
<p style="margin: 6pt 0cm;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-indent: 0px;text-decoration: none;text-align: justify;"><span style='font-size:15px;font-family: "Trebuchet MS", sans-serif;color: black;'>Sur le terrain, vous repr&eacute;sentez l&apos;Institut National de la Statistique (INS) de Guin&eacute;e. Vous devez faire preuve de professionnalisme dans vos relations avec les autorit&eacute;s administratives et les populations. La r&eacute;ussite de votre travail en d&eacute;pend. Soyez donc courtois et respectueux envers les autorit&eacute;s administratives et les populations.</span></p>
<p style="margin: 7.5pt 0cm;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-decoration: none;text-indent: 35.4pt;"><strong><span style='font-size:15px;font-family: "Trebuchet MS", sans-serif;color: black;'>2-</span></strong><strong><span style='font-size:15px;font-family: "Trebuchet MS", sans-serif;color: black;'>Ethiques et Valeurs</span></strong></p>
<p style="margin: 6pt 0cm;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;"><span style='font-size:15px;font-family: "Trebuchet MS", sans-serif;'>Au cours de vos interventions dans le cadre de cette op&eacute;ration, il vous est demand&eacute; d&apos;agir conform&eacute;ment &agrave; l&apos;&eacute;thique et aux valeurs suivantes.</span></p>
<p style="margin: 6pt 0cm;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;"><span style='font-size:15px;font-family: "Trebuchet MS", sans-serif;'>&nbsp;</span></p>
<p style="margin: 6pt 0cm;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;"><span style='font-size:15px;font-family: "Trebuchet MS", sans-serif;'>&nbsp;</span></p>
<p style="margin: 0cm 0cm 7.5pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-decoration: none;text-indent: 35.4pt;"><strong><span style='font-family: "Trebuchet MS", sans-serif;color: black;'>3-Int&eacute;grit&eacute;&nbsp;</span></strong></p>
<p style="margin: 0cm 0cm 7.5pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;"><span style='font-family: "Trebuchet MS", sans-serif;color: black;'>&nbsp;</span></p>
<p style="margin: 0cm 0cm 7.5pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;"><span style='font-family: "Trebuchet MS", sans-serif;color: black;'>Transcription exacte et fiable des d&eacute;clarations de l&apos;enqu&ecirc;t&eacute;(e) sans interpr&eacute;tation</span></p>
<p style="margin: 0cm 0cm 7.5pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;"><span style='font-family: "Trebuchet MS", sans-serif;color: black;'>&nbsp;</span></p>
<p style="margin: 0cm 0cm 7.5pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;"><strong><span style='font-family: "Trebuchet MS", sans-serif;color: black;'>4-Civisme</span></strong></p>
<p style="margin: 0cm 0cm 7.5pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;"><span style='font-family: "Trebuchet MS", sans-serif;color: black;'>&nbsp;</span></p>
<p style="margin: 0cm 0cm 7.5pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;"><span style='font-family: "Trebuchet MS", sans-serif;color: black;'>D&eacute;vouement envers la collectivit&eacute;, l&apos;Etat et &agrave; la participation r&eacute;guli&egrave;re &agrave; ses activit&eacute;s notamment par l&apos;exercice d&apos;une obligation donn&eacute;e.</span></p>
<p style="margin: 0cm 0cm 7.5pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;"><span style='font-family: "Trebuchet MS", sans-serif;color: black;'>&nbsp;</span></p>
<p style="margin: 0cm 0cm 7.5pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;"><strong><span style='font-family: "Trebuchet MS", sans-serif;color: black;'>5-Responsabilit&eacute;</span></strong></p>
<p style="margin: 0cm 0cm 7.5pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;"><strong><span style='font-family: "Trebuchet MS", sans-serif;color: black;'>&nbsp;</span></strong></p>
<p style="margin: 0cm 0cm 7.5pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;"><span style='font-family: "Trebuchet MS", sans-serif;color: black;'>Obligation ou n&eacute;cessit&eacute; morale de r&eacute;pondre, de se porter garant de ses actions ou de celles des autres mais qui implique que l&apos;on rende compte.</span></p>
<p style="margin: 0cm 0cm 7.5pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;"><span style='font-family: "Trebuchet MS", sans-serif;color: black;'>&nbsp;</span></p>
<p style="margin: 0cm 0cm 7.5pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;"><strong><span style='font-family: "Trebuchet MS", sans-serif;color: black;'>6-Esprit de discipline&nbsp;</span></strong></p>
<p style="margin: 0cm 0cm 7.5pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;"><strong><span style='font-family: "Trebuchet MS", sans-serif;color: black;'>&nbsp;</span></strong></p>
<p style="margin: 0cm 0cm 7.5pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;"><span style='font-family: "Trebuchet MS", sans-serif;color: black;'>Aptitude &agrave; ob&eacute;ir, &agrave; se soumettre aux r&egrave;gles de l&apos;institution qui vous emploie ou au groupe auquel on appartient.</span></p>
<p style="margin: 0cm 0cm 7.5pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;"><span style='font-family: "Trebuchet MS", sans-serif;color: black;'>&nbsp;</span></p>
<p style="margin: 0cm 0cm 7.5pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;"><strong><span style='font-family: "Trebuchet MS", sans-serif;color: black;'>7-Esprit d&apos;&eacute;quipe&nbsp;</span></strong></p>
<p style="margin: 0cm 0cm 7.5pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;"><strong><span style='font-family: "Trebuchet MS", sans-serif;color: black;'>&nbsp;</span></strong></p>
<p style="margin: 0cm 0cm 7.5pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;"><span style='font-family: "Trebuchet MS", sans-serif;color: black;'>Aptitude d&apos;un groupe d&apos;individus qui, &agrave; divers postes, travaillant pendant une m&ecirc;me p&eacute;riode de temps &agrave; atteindre un m&ecirc;me objectif, conform&eacute;ment &agrave; des objectifs vis&eacute;s.</span></p>
<p style="margin: 0cm 0cm 7.5pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;"><span style='font-family: "Trebuchet MS", sans-serif;color: black;'>&nbsp;</span></p>
<p style="margin: 0cm 0cm 7.5pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;"><strong><span style='font-family: "Trebuchet MS", sans-serif;color: black;'>8-Respect du droit et des m&oelig;urs locales en vigueur&nbsp;</span></strong></p>
<p style="margin: 0cm 0cm 7.5pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;"><strong><span style='font-family: "Trebuchet MS", sans-serif;color: black;'>&nbsp;</span></strong></p>
<p style="margin: 0cm 0cm 7.5pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;"><span style='font-family: "Trebuchet MS", sans-serif;color: black;'>Aptitude &agrave; accorder de la consid&eacute;ration du respect et de la valeur au droit et aux m&oelig;urs locales des individus approch&eacute;s quel que soit leur statut.</span></p>
<p style="margin: 0cm 0cm 7.5pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;"><span style='font-family: "Trebuchet MS", sans-serif;color: black;'>&nbsp;</span></p>
<p style="margin: 0cm 0cm 7.5pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;"><strong><span style='font-family: "Trebuchet MS", sans-serif;color: black;'>9-Respect des autorit&eacute;s &agrave; tous les &eacute;chelons</span></strong></p>
<p style="margin: 0cm 0cm 7.5pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;"><strong><span style='font-family: "Trebuchet MS", sans-serif;color: black;'>&nbsp;</span></strong></p>
<p style="margin: 0cm 0cm 7.5pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;"><span style='font-family: "Trebuchet MS", sans-serif;color: black;'>Aptitude &agrave; accorder de la consid&eacute;ration, du respect et de la valeur &agrave; l&apos;autorit&eacute; en face de qui l&apos;on est en pr&eacute;sence.</span></p>
<p style="margin: 0cm 0cm 7.5pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;"><span style='font-family: "Trebuchet MS", sans-serif;color: black;'>&nbsp;</span></p>
<p style="margin: 0cm 0cm 7.5pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;"><strong><span style='font-family: "Trebuchet MS", sans-serif;color: black;'>10-Respect de la hi&eacute;rarchie &agrave; tous les &eacute;chelons</span></strong></p>
<p style="margin: 0cm 0cm 7.5pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;"><span style='font-family: "Trebuchet MS", sans-serif;color: black;'>&nbsp;</span></p>
<p style="margin: 0cm 0cm 7.5pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;"><span style='font-family: "Trebuchet MS", sans-serif;color: black;'>Aptitude &agrave; accorder de la consid&eacute;ration, du respect et de la valeur &agrave; la hi&eacute;rarchie quel que soit son niveau.</span></p>
<p style="margin: 0cm 0cm 7.5pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;"><span style='font-family: "Trebuchet MS", sans-serif;color: black;'>&nbsp;</span></p>
<p style="margin: 0cm 0cm 7.5pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;"><strong><span style='font-family: "Trebuchet MS", sans-serif;color: black;'>11-Respect des m&eacute;nages et des enqu&ecirc;t&eacute;s</span></strong></p>
<p style="margin: 0cm 0cm 7.5pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;"><span style='font-family: "Trebuchet MS", sans-serif;color: black;'>&nbsp;</span></p>
<p style="margin: 0cm 0cm 7.5pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;"><span style='font-family: "Trebuchet MS", sans-serif;color: black;'>Aptitude &agrave; accorder de la consid&eacute;ration, du respect et de la valeur aux m&eacute;nages (chef, autres membres enqu&ecirc;t&eacute;s)</span></p>
<p style="margin: 0cm 0cm 7.5pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;"><span style='font-family: "Trebuchet MS", sans-serif;color: black;'>&nbsp;</span></p>
<p style="margin: 0cm 0cm 7.5pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;"><strong><span style='font-family: "Trebuchet MS", sans-serif;color: black;'>12-Assiduit&eacute;&nbsp;</span></strong></p>
<p style="margin: 0cm 0cm 7.5pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;"><strong><span style='font-family: "Trebuchet MS", sans-serif;color: black;'>&nbsp;</span></strong></p>
<p style="margin: 0cm 0cm 7.5pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;"><span style='font-family: "Trebuchet MS", sans-serif;color: black;'>Aptitude &agrave; se trouver l&agrave;&nbsp;&nbsp;on est appel&eacute; par ses fonctions ou par ses obligations, application constante &agrave; faire un&nbsp;travail, une action.</span></p>
<p style="margin: 0cm 0cm 7.5pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;"><strong><span style='font-family: "Trebuchet MS", sans-serif;color: black;'>&nbsp;</span></strong></p>
<p style="margin: 0cm 0cm 7.5pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;"><strong><span style='font-family: "Trebuchet MS", sans-serif;color: black;'>13-Ponctualit&eacute;</span></strong></p>
<p style="margin: 0cm 0cm 7.5pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;"><strong><span style='font-family: "Trebuchet MS", sans-serif;color: black;'>&nbsp;</span></strong></p>
<p style="margin: 0cm 0cm 7.5pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;"><span style='font-family: "Trebuchet MS", sans-serif;color: black;'>Qualit&eacute; de quelqu&apos;un qui arrive toujours &agrave; l&apos;heure.</span></p>
<p style="margin: 0cm 0cm 7.5pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;"><span style='font-family: "Trebuchet MS", sans-serif;color: black;'>&nbsp;</span></p>
<p style="margin: 0cm 0cm 7.5pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;"><span style='font-family: "Trebuchet MS", sans-serif;color: black;'>&nbsp;</span></p>
<p style="margin: 0cm 0cm 7.5pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;"><span style='font-family: "Trebuchet MS", sans-serif;color: black;'>&nbsp;</span></p>
<p style="margin: 0cm 0cm 7.5pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;"><span style='font-family: "Trebuchet MS", sans-serif;color: black;'>&nbsp;</span></p>
<p style="margin: 0cm 0cm 7.5pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;"><strong><span style='font-family: "Trebuchet MS", sans-serif;color: black;'>14-Avoir une bonne tenue vestimentaire et &ecirc;tre pr&eacute;sentable</span></strong></p>
<p style="margin: 0cm 0cm 7.5pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;"><strong><span style='font-family: "Trebuchet MS", sans-serif;color: black;'>&nbsp;</span></strong></p>
<p style="margin: 0cm 0cm 7.5pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;"><span style='font-family: "Trebuchet MS", sans-serif;color: black;'>Porter une tenue suffisamment d&eacute;cente, propre, etc� pour pouvoir se pr&eacute;senter, se montrer &agrave; quelqu&apos;un.</span></p>
<p style="margin: 0cm 0cm 7.5pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;"><span style='font-family: "Trebuchet MS", sans-serif;color: black;'>&nbsp;</span></p>
<p style="margin: 0cm 0cm 7.5pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;"><span style='font-family: "Trebuchet MS", sans-serif;color: black;'>&nbsp;</span></p>
<p style="margin: 0cm 0cm 7.5pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;"><strong><span style='font-family: "Trebuchet MS", sans-serif;color: black;'>15-Engagement envers le code</span></strong></p>
<p style="margin: 0cm 0cm 7.5pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;"><strong><span style='font-family: "Trebuchet MS", sans-serif;color: black;'>&nbsp;</span></strong></p>
<p style="margin: 0cm 0cm 7.5pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;"><span style='font-family: "Trebuchet MS", sans-serif;color: black;'>Disposition, acte par lequel on s&apos;engage &agrave; accomplir, &agrave; tenir la promesse faite de respecter les principales clauses du code de bonne conduite qui est annex&eacute; &agrave; tout contrat sign&eacute; dans le cadre des activit&eacute;s du BCR<strong>.</strong></span></p>
<p style="margin: 0cm 0cm 7.5pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;"><strong><span style='font-family: "Trebuchet MS", sans-serif;color: black;'>&nbsp;</span></strong></p>
<p style="margin: 0cm 0cm 7.5pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;"><strong><span style='font-family: "Trebuchet MS", sans-serif;color: black;'>&nbsp;</span></strong></p>
<p style="margin: 0cm 0cm 7.5pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-indent: 0px;text-decoration: none;text-align: center;"><strong><span style='font-family: "Trebuchet MS", sans-serif;color: black;'>AVERTISSEMENTS</span></strong></p>
<p style="margin: 7.5pt 0cm;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-decoration: none;text-indent: 35.4pt;"><strong><span style='font-size:15px;font-family: "Trebuchet MS", sans-serif;color: black;'>1-Signaler les manquements pr&eacute;sum&eacute;s du code</span></strong></p>
<p style="margin: 6pt 0cm;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-indent: 0px;text-decoration: none;text-align: justify;"><span style='font-size:15px;font-family: "Trebuchet MS", sans-serif;color: black;'>Chacun de nous a l&apos;obligation de faire observer ce code de bonne conduite. Si vous observez un comportement qui vous pr&eacute;occupe, ou qui est susceptible de repr&eacute;senter une violation de ce Code, informez les autorit&eacute;s de l&apos;INS par voie hi&eacute;rarchique. En agissant ainsi, vous donnez &agrave; l&apos;INS la possibilit&eacute; d&apos;&eacute;lucider la situation et d&apos;y rem&eacute;dier, le cas &eacute;ch&eacute;ant. Il est &agrave; signaler qu&apos;un agent n&apos;encourt aucune sanction en d&eacute;non&ccedil;ant une violation du pr&eacute;sent code. Toutefois, les calomnies sont une attitude &agrave; proscrire</span></p>
<p style="margin: 7.5pt 0cm;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-decoration: none;text-indent: 35.4pt;"><strong><span style='font-size:15px;font-family: "Trebuchet MS", sans-serif;color: black;'>2-Harc&egrave;lementet intimidation</span></strong></p>
<p style="margin: 6pt 0cm;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-indent: 0px;text-decoration: none;text-align: justify;"><span style='font-size:15px;font-family: "Trebuchet MS", sans-serif;color: black;'>Nous nous engageons &agrave; faire en sorte que nos Agents et nos partenaires travaillent dans un environnement s&ocirc;r et respectueux, exempt d&apos;intimidation sous toutes ses formes.</span></p>
<p style="margin: 6pt 0cm;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-indent: 0px;text-decoration: none;text-align: justify;"><span style='font-size:15px;font-family: "Trebuchet MS", sans-serif;color: black;'>Traitez tous les Agents, partenaires et autres parties prenantes avec dignit&eacute; et respect en tout temps.</span></p>
<p style="margin: 6pt 0cm;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-indent: 0px;text-decoration: none;text-align: justify;"><span style='font-size:15px;font-family: "Trebuchet MS", sans-serif;color: black;'>Tout type de harc&egrave;lement ou d&apos;intimidation, y compris physique, sexuel, verbal ou autre, est interdit et peut entraver des mesures disciplinaires.</span></p>
<p style="margin: 7.5pt 0cm;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-decoration: none;text-indent: 35.4pt;"><strong><span style='font-size:15px;font-family: "Trebuchet MS", sans-serif;color: black;'>6-Fiabilit&eacute; des donn&eacute;es collect&eacute;es</span></strong></p>
<p style="margin: 6pt 0cm;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-indent: 0px;text-decoration: none;text-align: justify;"><span style='font-size:15px;font-family: "Trebuchet MS", sans-serif;color: black;'>Les donn&eacute;es collect&eacute;es lors du Recensement G&eacute;n&eacute;ral de la Population&nbsp;&nbsp;et l&rsquo;Habitation nformations collect&eacute;es (int&eacute;grit&eacute;).</span></p>
<p style="margin: 7.5pt 0cm;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-decoration: none;text-indent: 35.4pt;"><strong><span style='font-size:15px;font-family: "Trebuchet MS", sans-serif;color: black;'>7-Protection des biens appartenant &agrave; l&apos;INS</span></strong></p>
<p style="margin: 6pt 0cm;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-indent: 0px;text-decoration: none;text-align: justify;"><span style='font-size:15px;font-family: "Trebuchet MS", sans-serif;color: black;'>Tous les biens et mat&eacute;riels du Recensement G&eacute;n&eacute;ral de la Population de l&rsquo;Habitation&nbsp;&nbsp;doivent &ecirc;tre utilis&eacute;s &agrave; des fins l&eacute;gitimes, efficacement et uniquement dans le cadre du projet. Ces biens et mat&eacute;riels ne doivent pas &ecirc;tre utilis&eacute;s &agrave; des fins personnelles.</span></p>
<p style="margin: 6pt 0cm;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-indent: 0px;text-decoration: none;text-align: justify;"><span style='font-size:15px;font-family: "Trebuchet MS", sans-serif;color: black;'>Les biens et mat&eacute;riels du projet comprennent notamment les ordinateurs, imprimantes, photocopieurs, tablettes, powerbank, les laptops et les syst&egrave;mes d&apos;information, les voitures, les t&eacute;l&eacute;phones, les informations confidentielles, les cl&eacute;s USB, etc.</span></p>
<p style="margin: 6pt 0cm;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-indent: 0px;text-decoration: none;text-align: justify;"><span style='font-size:15px;font-family: "Trebuchet MS", sans-serif;color: black;'>L&apos;Agent s&apos;engage &agrave; prendre soin du mat&eacute;riel de travail que l&apos;employeur met &agrave; sa disposition, et &agrave; le lui rendre en bon &eacute;tat &agrave; la fin du projet, sous peine de sanction disciplinaire et sans pr&eacute;judice de poursuites judiciaires &agrave; l&apos;encontre de l&apos;agent.&nbsp;</span></p>
<p style="margin: 6pt 0cm;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-indent: 0px;text-decoration: none;text-align: justify;"><span style='font-size:15px;font-family: "Trebuchet MS", sans-serif;color: black;'>En cas de soup&ccedil;on de fraude, de vol, de n&eacute;gligence ou d&apos;abus, chaque Agent a l&apos;obligation d&apos;en informer sa hi&eacute;rarchie.</span></p>
<p style="margin: 7.5pt 0cm;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-decoration: none;text-indent: 35.4pt;"><strong><span style="font-size:15px;font-family: Gotham-Book, serif;color: black;">8-Autres agissements &agrave; proscrire</span></strong></p>
<p style="margin: 6pt 0cm;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-indent: 0px;text-decoration: none;text-align: justify;"><span style='font-size:15px;font-family: "Trebuchet MS", sans-serif;color: black;'>Chaque agent intervenant sur le Recensement G&eacute;n&eacute;ral&nbsp;&nbsp;de la Population et de l&apos;Habitation&nbsp;&nbsp;RGPH-4&nbsp;&nbsp;doit s&apos;abstenir de&nbsp;:</span></p>
<p style="margin: 0cm 0cm 7.5pt 18pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-decoration: none;text-indent: -18pt;"><span style="font-family: -webkit-standard, serif;color: black;">-&nbsp;</span><span style='font-family: "Trebuchet MS", sans-serif;color: black;'>D&eacute;l&eacute;guer ses fonctions &agrave; une autre personne&nbsp;;</span></p>
<p style="margin: 0cm 0cm 7.5pt 18pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-decoration: none;text-indent: -18pt;"><span style="font-family: -webkit-standard, serif;color: black;">-&nbsp;</span><span style='font-family: "Trebuchet MS", sans-serif;color: black;'>Se faire accompagner dans son travail par d&apos;autres personnes ext&eacute;rieures au projet sans l&apos;autorisation de son sup&eacute;rieur hi&eacute;rarchique&nbsp;;</span></p>
<p style="margin: 0cm 0cm 7.5pt 18pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-decoration: none;text-indent: -18pt;"><span style="font-family: -webkit-standard, serif;color: black;">-&nbsp;</span><span style='font-family: "Trebuchet MS", sans-serif;color: black;'>Transporter une tierce personne dans le v&eacute;hicule de mission&nbsp;;</span></p>
<p style="margin: 0cm 0cm 7.5pt 18pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-decoration: none;text-indent: -18pt;"><span style="font-family: -webkit-standard, serif;color: black;">-&nbsp;</span><span style='font-family: "Trebuchet MS", sans-serif;color: black;'>Demander aux populations des renseignements qui ne figurent pas sur le questionnaire&nbsp;ou qui n&apos;ont aucun rapport avec sa mission ;</span></p>
<p style="margin: 0cm 0cm 7.5pt 18pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-decoration: none;text-indent: -18pt;"><span style="font-family: -webkit-standard, serif;color: black;">-&nbsp;</span><span style='font-family: "Trebuchet MS", sans-serif;color: black;'>Faire des promesses non fond&eacute;es &agrave; la population&nbsp;;</span></p>
<p style="margin: 0cm 0cm 7.5pt 18pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-decoration: none;text-indent: -18pt;"><span style="font-family: -webkit-standard, serif;color: black;">-&nbsp;</span><span style='font-family: "Trebuchet MS", sans-serif;color: black;'>Communiquer ou faire des commentaires sur les donn&eacute;es recueillies lors du recensement&nbsp;;</span></p>
<p style="margin: 0cm 0cm 7.5pt 18pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-decoration: none;text-indent: -18pt;"><span style="font-family: -webkit-standard, serif;color: black;">-&nbsp;</span><span style='font-family: "Trebuchet MS", sans-serif;color: black;'>Tenir des discussions sur des sujets sensibles (d&apos;ordre politique, religieux, etc.) pendant la collecte des donn&eacute;es&nbsp;;</span></p>
<p style="margin: 0cm 0cm 7.5pt 18pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-decoration: none;text-indent: -18pt;"><span style="font-family: -webkit-standard, serif;color: black;">-&nbsp;</span><span style='font-family: "Trebuchet MS", sans-serif;color: black;'>Se m&ecirc;ler &agrave; des conflits entre habitants&nbsp;;</span></p>
<p style="margin: 0cm 0cm 7.5pt 18pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-decoration: none;text-indent: -18pt;"><span style="font-family: -webkit-standard, serif;color: black;">-&nbsp;</span><span style='font-family: "Trebuchet MS", sans-serif;color: black;'>Se livrer &agrave; des activit&eacute;s autres que celles du recensement&nbsp;;</span></p>
<p style="margin: 0cm 0cm 7.5pt 18pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-decoration: none;text-indent: -18pt;"><span style="font-family: -webkit-standard, serif;color: black;">-&nbsp;</span><span style='font-family: "Trebuchet MS", sans-serif;color: black;'>Abandonner son travail pour s&apos;adonner &agrave; des activit&eacute;s extra-professionnelles dans le cadre de sa mission&nbsp;;</span></p>
<p style="margin: 0cm 0cm 7.5pt 18pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-decoration: none;text-indent: -18pt;"><span style="font-family: -webkit-standard, serif;color: black;">-&nbsp;</span><span style='font-family: "Trebuchet MS", sans-serif;color: black;'>Consommer de l&apos;alcool durant les heures de travail&nbsp;;</span></p>
<p style="margin: 0cm 0cm 7.5pt 18pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-decoration: none;text-indent: -18pt;"><span style="font-family: -webkit-standard, serif;color: black;">-&nbsp;</span><span style='font-family: "Trebuchet MS", sans-serif;color: black;'>Porter atteinte &agrave; l&apos;image de marque de l&apos;INS &nbsp;Guin&eacute;e</span></p>
<p style="margin: 0cm 0cm 7.5pt 18pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-decoration: none;text-indent: -18pt;"><span style="font-family: -webkit-standard, serif;color: black;">-&nbsp;</span><span style='font-family: "Trebuchet MS", sans-serif;color: black;'>Se livrer &agrave; des rixes envers un membre de l&apos;&eacute;quipe ou des tiers&nbsp;;</span></p>
<p style="margin: 0cm 0cm 7.5pt 18pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-decoration: none;text-indent: -18pt;"><span style="font-family: -webkit-standard, serif;color: black;">-&nbsp;</span><span style='font-family: "Trebuchet MS", sans-serif;color: black;'>Prof&eacute;rer des injures, menaces et voie de faits envers un membre de l&apos;&eacute;quipe ou des tiers&nbsp;;</span></p>
<p style="margin: 0cm 0cm 7.5pt 18pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-decoration: none;text-indent: -18pt;"><span style="font-family: -webkit-standard, serif;color: black;">-&nbsp;</span><span style='font-family: "Trebuchet MS", sans-serif;color: black;'>Inciter les autres membres de l&apos;&eacute;quipe &agrave; la d&eacute;sob&eacute;issance&nbsp;;</span></p>
<p style="margin: 0cm 0cm 7.5pt 18pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-decoration: none;text-indent: -18pt;"><span style="font-family: -webkit-standard, serif;color: black;">-&nbsp;</span><span style='font-family: "Trebuchet MS", sans-serif;color: black;'>Refuser de rejoindre son lieu de travail&nbsp;;</span></p>
<p style="margin: 0cm 0cm 7.5pt 18pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-decoration: none;text-indent: -18pt;"><span style="font-family: -webkit-standard, serif;color: black;">-&nbsp;</span><span style='font-family: "Trebuchet MS", sans-serif;color: black;'>Faire preuve de mauvaise volont&eacute; dans l&apos;accomplissement de sa t&acirc;che&nbsp;;</span></p>
<p style="margin: 0cm 0cm 7.5pt 18pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-decoration: none;text-indent: -18pt;"><span style="font-family: -webkit-standard, serif;color: black;">-&nbsp;</span><span style='font-family: "Trebuchet MS", sans-serif;color: black;'>Abimer le mat&eacute;riel de travail.</span></p>
<p style="margin: 0cm 0cm 7.5pt 18pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;"><span style='font-family: "Trebuchet MS", sans-serif;color: black;'>&nbsp;</span></p>
<p style="margin: 6pt 0cm;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-indent: 0px;text-decoration: none;text-align: justify;"><span style='font-size:15px;font-family: "Trebuchet MS", sans-serif;color: black;'>Ce code de bonne conduite fait partie int&eacute;grante du contrat sign&eacute; par chaque Agent.</span></p>
<p style="margin: 6pt 0cm;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-indent: 0px;text-decoration: none;text-align: justify;"><span style='font-size:15px;font-family: "Trebuchet MS", sans-serif;color: black;'>En signant son contrat de travail, l&apos;agent s&apos;engage &agrave; respecter scrupuleusement les prescriptions de ce code de bonne conduite &agrave; mener &agrave; bien l&apos;ex&eacute;cution des travaux &agrave; lui confier.</span></p>
<p style="margin: 6pt 0cm;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-indent: 0px;text-decoration: none;text-align: justify;"><span style='font-size:15px;font-family: "Trebuchet MS", sans-serif;color: black;'>&nbsp;</span></p>
<p style="margin: 18pt 0cm 6pt 318.6pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-decoration: none;text-align: justify;text-indent: 35.4pt;"><strong><span style='font-size:15px;font-family: "Trebuchet MS", sans-serif;color: black;'>Le Coordonnateur National&nbsp;</span></strong></p>

        </div>
        <div id="<?php echo $projet['id'];?>" style="margin:0; margin-top:20px;padding-bottom:10px; font-weight: bold">
            <input type="checkbox" name="lubonneconduite" value="1" required>J'ai lu le code de bonne conduite et j'approuve<br>
        </div>
    
</div>

